function importqqqures2()
  txd = engineLoadTXD("object/akina.txd")
  engineImportTXD(txd, 3923)
  col = engineLoadCOL("object/akina1.col")
  dff = engineLoadDFF("object/akina1.dff", 0)
  engineReplaceCOL(col, 3923)
  engineReplaceModel(dff, 3923)
  engineSetModelLODDistance(3923, 2000)
end
setTimer(importqqqures2, 3923, 1)
addEventHandler("onClientResourceStop", getResourceRootElement(getThisResource()), function()
  engineRestoreCOL(3923)
  engineRestoreModel(3923)
  destroyElement(dff)
  destroyElement(col)
  destroyElement(txd)
end)
function importqqqures2()
  txd = engineLoadTXD("object/akina.txd")
  engineImportTXD(txd, 3911)
  col = engineLoadCOL("object/akina2.col")
  dff = engineLoadDFF("object/akina2.dff", 0)
  engineReplaceCOL(col, 3911)
  engineReplaceModel(dff, 3911)
  engineSetModelLODDistance(3911, 2000)
end
setTimer(importqqqures2, 3000, 1)
addEventHandler("onClientResourceStop", getResourceRootElement(getThisResource()), function()
  engineRestoreCOL(3911)
  engineRestoreModel(3911)
  destroyElement(dff)
  destroyElement(col)
  destroyElement(txd)
end)
function importqqqures2()
  txd = engineLoadTXD("object/akina.txd")
  engineImportTXD(txd, 3907)
  col = engineLoadCOL("object/akina3.col")
  dff = engineLoadDFF("object/akina3.dff", 0)
  engineReplaceCOL(col, 3907)
  engineReplaceModel(dff, 3907)
  engineSetModelLODDistance(3907, 2000)
end
setTimer(importqqqures2, 3000, 1)
addEventHandler("onClientResourceStop", getResourceRootElement(getThisResource()), function()
  engineRestoreCOL(3907)
  engineRestoreModel(3907)
  destroyElement(dff)
  destroyElement(col)
  destroyElement(txd)
end)
function importqqqures2()
  txd = engineLoadTXD("object/akina.txd")
  engineImportTXD(txd, 3906)
  col = engineLoadCOL("object/akina4.col")
  dff = engineLoadDFF("object/akina4.dff", 0)
  engineReplaceCOL(col, 3906)
  engineReplaceModel(dff, 3906)
  engineSetModelLODDistance(3906, 2000)
end
setTimer(importqqqures2, 3000, 1)
addEventHandler("onClientResourceStop", getResourceRootElement(getThisResource()), function()
  engineRestoreCOL(3906)
  engineRestoreModel(3906)
  destroyElement(dff)
  destroyElement(col)
  destroyElement(txd)
end)
function importqqqures2()
  txd = engineLoadTXD("object/akina.txd")
  engineImportTXD(txd, 3905)
  col = engineLoadCOL("object/akina5.col")
  dff = engineLoadDFF("object/akina5.dff", 0)
  engineReplaceCOL(col, 3905)
  engineReplaceModel(dff, 3905)
  engineSetModelLODDistance(3905, 2000)
end
setTimer(importqqqures2, 3000, 1)
addEventHandler("onClientResourceStop", getResourceRootElement(getThisResource()), function()
  engineRestoreCOL(3905)
  engineRestoreModel(3905)
  destroyElement(dff)
  destroyElement(col)
  destroyElement(txd)
end)
